[tasks.format-check]
run = 'go mod tidy --diff && if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi'

[tasks.lint]
run = 'golangci-lint run'

[tasks.build]
run = 'go build -v ./...'

[tasks.test]
depends = [":build"]
run = 'go test -v ./...'

[tasks.check]
depends = [':format-check', ':lint', ':test']
