name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-2024:
    name: "//2024:check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
        with:
          experimental: true
      - run: mise '//2024:check'
  check-2025:
    name: "//2025:check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
        with:
          experimental: true
      - run: mise '//2025:check'
