name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: "Lint/Build/Test"
    runs-on: ubuntu-latest
    env:
      MISE_LOCKED: 1
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - name: Run all tests
        run: mise '//...:test*' --jobs 4
